# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from images import bluetooth_image

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(264, 156)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(window.sizePolicy().hasHeightForWidth())
        window.setSizePolicy(sizePolicy)
        window.setMinimumSize(QtCore.QSize(264, 156))
        window.setMaximumSize(QtCore.QSize(264, 156))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bt_image/bluetooth_window_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        window.setWindowIcon(icon)
        window.setAutoFillBackground(False)
        window.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.load_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_button.setGeometry(QtCore.QRect(5, 5, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_button.sizePolicy().hasHeightForWidth())
        self.load_button.setSizePolicy(sizePolicy)
        self.load_button.setObjectName("load_button")
        self.listBox = QtWidgets.QListWidget(self.centralwidget)
        self.listBox.setGeometry(QtCore.QRect(4, 40, 256, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listBox.sizePolicy().hasHeightForWidth())
        self.listBox.setSizePolicy(sizePolicy)
        self.listBox.setObjectName("listBox")
        self.bt_icon = QtWidgets.QLabel(self.centralwidget)
        self.bt_icon.setGeometry(QtCore.QRect(74, 8, 17, 25))
        self.bt_icon.setText("")
        self.bt_icon.setPixmap(QtGui.QPixmap(":/bt_image/bluetooth_image.png"))
        self.bt_icon.setScaledContents(False)
        self.bt_icon.setObjectName("bt_icon")
        window.setCentralWidget(self.centralwidget)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Headsets"))
        self.load_button.setText(_translate("window", "Load"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
